name: "CI/CD"
on: [push]

env:
  CI: "true"
  CODECOV: "true"

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        if: "github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop -P
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.3.0
        if: "github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake test_app
        name: Create test app
      - run: mkdir -p ./spec/decidim_dummy_app/tmp/screenshots
        name: Create the screenshots folder
      - uses: nanasess/setup-chromedriver@v1.0.1
      - name: Run precompile if needed
        run: |
          if [[ -d "app/views" ]] || [[ -d "spec/mailers" ]] || [[ -d "spec/system" ]]; then
            cd "spec/decidim_dummy_app"
            bundle exec rails assets:precompile
          else
            echo "No need to precompile assets since system folder is empty"
          fi
      - run: bundle exec rspec
        name: RSpec
      - uses: codecov/codecov-action@v1
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
          if-no-files-found: ignore
  release:
    if: "github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'"
    needs: [tests, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup git and gh
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
      - run: gem install parse_gemspec-cli
        name: Intall gem parser
      - run: echo "::set-output name=tag::$(parse-gemspec-cli *.gemspec | jq .'version')"
        name: Set tag version
        id: set_tag
      - name: Add tag and push
        run: |
          git tag
          git push --tags
      - name: Create release
        run: gh release create ${{ steps.set_tag.outputs.tag }} --generate-notes
  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_API_KEY}}"